project:
  type: website
  output-dir: docs

website:
  title: "marketbasket.in.ua"
  site-url: https://www.marketbasket.in.ua
  description: "Ринкова вартість споживчого кошика в Україні"
  image: foodset.png
  favicon: myfavicon.png
  open-graph: true
  page-navigation: true
  twitter-card: true
  navbar:
    left:
      - text: "Про проєкт"
        href: index.qmd
      - text: "Дані" 
        href: data.qmd
      - text: "Аналіз"
        href: analysis.qmd
      - text: "Про себе" 
        href: about.qmd
     
format:
  html:
    theme: Flatly
    css: styles.css
    toc: true
    toc-location: left
    toc-title: На цій сторінці
    code-overflow: wrap

editor: visual

