project:
  type: website
  output-dir: docs

website:
  description: "В цьому проєкті я налаштовую автоматичний збір цін на визначені державою групи товарів та послуг, що складають споживчий кошик"
  favicon: myfavicon.png
  open-graph:
    image: "https://github.com/myku3in/market-basket-pages/blob/main/docs/foodset.png"
    description: "В цьому проєкті я налаштовую автоматичний збір цін на визначені державою групи товарів та послуг, що складають споживчий кошик"
  twitter-card: true
  page-navigation: true
  navbar:
    left:
      - text: "Про проєкт"
        href: index.qmd
      - text: "Дані" 
        href: data.qmd
      - text: "Аналіз"
        href: analysis.qmd
      - text: "Про себе" 
        href: about.qmd
  search:
    location: navbar
    type: overlay
     
format:
  html:
    theme: Flatly
    css: styles.css
    toc: true
    toc-location: left
    toc-title: На цій сторінці
    code-overflow: wrap

editor: visual

