---
title: "Ринкова вартість споживчого кошика"
---

## Ідея проєкту

Вітаю на сторінці публічного проєкту "Ринкова вартість споживчого кошика".

Ідея цього проєкту виникла з розмов, на які я натрапляв неодноразово: прожитковий мінімум в Україні не дозволяє забезпечити базові потреби людини. Сума у 2,684 грн для працездатної особи (станом на 1 січня 2023 року) справді ледве перевищує визначену Світовим банком [межу бідності](https://www.worldbank.org/en/news/factsheet/2022/05/02/fact-sheet-an-adjustment-to-global-poverty-lines), що сьогодні становить 2.15 дол/день. Але що закладається нашою державою у цей соціальний стандарт і якою є ринкова вартість задоволення базових потреб людини? Більше того, що слід відносити до базових потреб?

Тож для початку я вирішив налаштувати автоматичний збір цін на визначені державою групи товарів та послуг, що складають споживчий кошик (з якого розраховується прожитковий мінімум), порахувати вартість споживчого кошика за актуальними ринковими цінами, і зробити ці дані відкритими.

Відтак, на цих сторінках ви знайдете:

-   почищені дані з цінами на рівні окремих товарів та послуг, що складають споживчий кошик в Україні;
-   зможете слідкувати за зміною вартості споживчого кошика за цінами найбільших ритейлерів та провайдерів послуг в Україні;
-   тут я також ділитимусь своїми думками і розвідками, оскільки ця тема стосується багатьох цікавих економічних та філософських категорій.

::: callout-note
"Cпоживчий кошик" не тотожний "споживчому набору", зі зміни вартості якого розраховується споживча інфляція. Державна служба статистики публікує регулярні [роз'яснення](https://ukrstat.gov.ua/Noviny/new_old/new2011/zmist/r_2.htm), що ці поняття не треба плутати. Цей проєкт не про інфляцію, а про адекватність розміра прожиткового мінімуму декларованим державою соціальним стандартам.
:::

## Хіба ці дані не доступні публічно?

Державна служба статистики України публікує щомісячні дані з середніми цінами на споживчі товари та послуги. Втім, у відкритому доступі є лише агреговані показники. В цьому проєкті я хочу зробити доступними ціни на рівні окремих продуктів та послуг, все почистити, звести до купи і зробити вікритим для дослідників, полісі-мейкерів і усіх інших, кому це цікаво.

Все, що тут робиться доступно у відкритому доступі, включно зі скриптом для збору інформації. Це мій pet project, оновлення з'являтимуться поступово. Контакти для зворотнього зв'язку є на цій сторінці.
